// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-template/internal/api/handlers/routes"
	user2 "go-template/internal/api/handlers/user"
	"go-template/internal/configs"
	"go-template/internal/repository"
	"go-template/internal/server"
	"go-template/internal/services/user"
	"go-template/internal/utils/database"
	"go-template/internal/utils/jwt"
	"net/http"
)

import (
	_ "go-template/assets/swagger"
)

// Injectors from wire.go:

// InitializeServer 使用 Wire 進行依賴注入，初始化 HTTP server
func InitializeServer(cfg *configs.Config) (*http.Server, func(), error) {
	db := database.Start(cfg)
	service := jwt.NewService(cfg)
	userRepository := repository.NewUserRepository(db)
	userService := user.NewUserService(userRepository, service)
	handler := user2.NewHandler(userService)
	userRoutes := routes.NewUser(handler, service)
	config := server.Config{
		DB:          db,
		JwtService:  service,
		UserService: userRoutes,
		Config:      cfg,
	}
	httpServer := server.Start(config)
	return httpServer, func() {
	}, nil
}
